---
- name: Picard Playbook
  hosts: all
  vars:
    cert_path: /docker/certs
    # customization for atosatto.docker-swarm role
    docker_daemon_config:
      hosts: ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2376"]
      # using the ext4 40GB partition we created before
      data-root: "/docker"
      storage-driver: "overlay2"
      tlsverify: true
      tlscacert: /docker/certs/CA.crt
      tlscert: /docker/certs/host.crt
      tlskey: /docker/certs/host.pem

    # override is needed to disable standard dockerd parameters
    docker_service_override: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
    # vagrant/vbox is providing 2 ip address with 2 different interfaces, eth1
    # is the one used for the internal network.
    # Both interface and ip selection could be improved...
    docker_swarm_interface: "eth1"
    docker_swarm_addr: 192.168.56.210
    copytocontroller: true
    skip_docker_compose: True

  roles:
    - setup
    - certificates
    - guybrush21.ansible_dockerswarm

  tasks:
    - name: deploy stack
      block:
        - name: install jsondiff and pyyaml
          pip:
            name:
              - jsondiff==2.0.0
              - pyyaml==6.0

        - name: copying ussenterprise image
          copy:
            src: "services"
            dest: "/docker"

        - name: eeploying ussenterprise image
          docker_stack:
            state: present
            name: "ussenterprise"
            compose:
              - "/docker/services/caddy/docker-compose.yml"
      when: "'docker_swarm_manager' in group_names"
