---
- name: Picard Playbook
  hosts: all
  become: true
  become_method: sudo
  vars:
    # customization for atosatto.docker-swarm role
    docker_daemon_config:
      hosts: ["unix:///var/run/docker.sock", "tcp://0.0.0.0:2375"]
      # using the ext4 40GB partition we created before
      data-root: "/docker"
      storage-driver: "overlay2"
    # override is needed to disable standard dockerd parameters
    docker_service_override: |
      [Service]
      ExecStart=
      ExecStart=/usr/bin/dockerd
    # vagrant/vbox is providing 2 ip address with 2 different interfaces, eth1
    # is the one used for the internal network.
    # Both interface and ip selection could be improved...
    docker_swarm_interface: "eth1"
    docker_swarm_addr: 192.168.56.210

  roles:
    - setup
    - atosatto.docker-swarm
