---
- name: install epel-release
  package:
    name: "epel-release"
    state: present

- name: install python-pip.
  package:
    state: present
    name:
      - "python-pip"
      - "python-setuptools"
      - "python-virtualenv"

- name: upgrade pip
  pip:
    name: pip
    state: latest
