- name: Enable epel repository
  yum:
    name:
      - epel-release
    state: present

- name: Install python environment
  yum:
    update_cache: true
    name:
      - python-pip
      - python-virtualenv
      - python-setuptools
    state: present
