---
- name: "Add new partition /dev/sda2"
  parted:
    device: "/dev/sda"
    number: "2"
    part_type: primary
    fs_type: xfs
    state: present
    resize: true
    part_start: "-40GB"

- name: Create a ext4 filesystem on /dev/sdb2
  community.general.filesystem:
    fstype: ext4
    dev: /dev/sda2

- name: "Create /docker directory if it does not exist"
  ansible.builtin.file:
    path: /docker
    state: directory
    mode: "0755"

- name: Mount and bind sdb2 on /docker
  ansible.posix.mount:
    path: /docker
    src: /dev/sda2
    opts: defaults,nofail
    state: mounted
    fstype: ext4
