---
- name: Remove existing docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

    state: absent

- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker official Centos repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Install docker
  yum:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: Ensure docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Install docker python module
  pip:
    name: docker

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy docker.service drop-in
  template:
    src: docker.service
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload Docker

- name: Copy daemon.json drop-in
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: Reload Docker
