---
- name: Remove existing docker packages
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine

    state: absent

- name: Add Docker repository
  yum_repository:
    name: docker-ce-stable
    description: Docker official Centos repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Install docker
  yum:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
